
name: CI
on: [push]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11.0]
        xcode: ['12', '12.1', '12.2']
        build_type: ['debug', 'release']
        exclude:
          - os: macos-11.0
            xcode: '12'
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Bundle install
        run: |
          bundle install
      - name: Fastlane build
        run: |
          bundle exec fastlane build_${{ matrix.build_type }}
