
name: CI
on: [push]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        xcode: [11.4, 11.5, 11.6, 11.7, 12.0]
        lane: [build_debug, build_release]
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Bundle install
        run: |
          bundle install
      - name: Fastlane build
        run: |
          bundle exec fastlane ${{ matrix.lane }}
